### PR TITLE
Add swiftpm 4 package manifest

### PR DESCRIPTION
**Pull request by sharplet**
As recommended in the [Version-specific manifest selection][manifest-version] section of the swiftpm docs, the `Package.swift` file (without any specific version suffix) should target the latest stable version of Swift.

This renames the existing `Package.swift` file to `Package@swift-3.swift`, and adds a new and updated version for Swift 4.

[manifest-version]: https://github.com/apple/swift-package-manager/blob/31e5affada8e354b66d3bda64f6e4245f5da5446/Documentation/Usage.md#version-specific-manifest-selection

### CODE REVIEW

**Comment by sharplet** [comment]
I also added a commit to update CI to use Xcode 9, which is required in order to test the Swift 4 package format.

**Comment by sharplet** [comment]
Unfortunately, the Swift 3 package manager, while it can consume a _dependency_ with both swift 3 & 4 manifest files, can't actually build the project directly.

**Review by chamander — APPROVED** [review]
Looks good, and CI is happy.

**Comment by michaelloo** [comment]
Hey @sharplet!

It seems that this needs to be updated now to support Xcode 9.4 instead of 9.2.

Also please correct me if I'm wrong, but this PR seems to only update the package manifest without actually updating the source to 9.4, is that the intention?

If yes, I have opened another PR to update the project to Xcode 9.4: https://github.com/outware/Scenarios/pull/38

It would be great to have your input!

**Comment by sharplet** [comment]
Yeah, this change wasn't intended to remove Swift 3 compatibility. I went head and updated CI to build against 9.4.

**Pull request merged**
